# Variables
@baseUrl = http://localhost:3333

# Health Check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Rooms
# @name createRooms
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "Essa é uma sala de teste"
}

###

@roomId = {{createRooms.response.body.$.roomId}}

###

# Get Room Question
# @name getRoomQuestion
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create Question
# @name createQuestion
POST {{baseUrl}}/rooms/809a9c56-036c-4717-9074-70d47bdc4956/questions
Content-Type: application/json

{
  "question": "O que é inteligência artificial"
}